In [4]:
import dash
from dash import dcc
from dash import html
from dash.dependencies import Input, Output
import pandas as pd
import plotly.express as px
import numpy as np 

# method to fromat the data for a line chart
# I can still write her 
def top(df_top):
    #create a empty datafram with said colmns
    df_formated = pd.DataFrame(columns = ["Country Name","year","data"])

    list_name = []

    #append the data for every year of every country
    for y in df_top.columns[4:24]:
        for z in df_top[y]:
            df_formated = df_formated.append({"year":y,"data":z},ignore_index=True)

    #get all of the Country Names in a list
    for x in range(0,20):
        temp_list = df_top["Country Name"].values
        for x in temp_list:
            list_name.append(x)

    #add the list of names to column Country Name
    df_formated["Country Name"] = list_name

    #sort the dataframe by both Country Name and year
    df_formated = df_formated.sort_values(["Country Name","year"])

    return df_formated

#read the csvs
df = pd.read_csv("data.csv")
df_income = pd.read_csv("income.csv")

year_list = []

#change the column names to the values in row 4
df.columns = df.iloc[3]

#drop the first 4 rows
df = df.drop(df.index[0:4])

# years were removing
for x in range(1960,2001):

    year_list.append(x)

#drop all of the columns with no data/little data
for x in year_list:

    df = df.drop(columns=[x])

#drop any rows with any None values
df = df.dropna()

#limit the columns to these
df_income = df_income[["Country Code","IncomeGroup"]]

# merge the two data frames on Country Code
df_merge = df.merge(df_income,how="inner",on="Country Code")

#df_merge = df_merge.dropna()

# all of the column names are numbers so change them all to strings
for x in range(2001,2021):
    df_merge = df_merge.rename(columns={x : str(x)})

#save the cleaned data to a csv
df_merge.to_csv("cleaned_data.csv")

#drop any rows with none values
df_merge = df_merge.dropna()

#create new column to show the change in the perecent from 2001 to 2020
df_merge["Rate of Change"] = df_merge["2020"] - df_merge["2001"]

df_merge

,Country Name,Country Code,Indicator Name,Indicator Code,2001,2002,2003,2004,2005,2006,...,2013,2014,2015,2016,2017,2018,2019,2020,IncomeGroup,Rate of Change
2,Angola,AGO,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS,15.454545,15.454545,15.454545,15.000000,15.000000,15.000000,...,34.090909,36.818182,36.818182,36.818182,30.454545,30.454545,30.000000,30.000000,Lower middle income,14.545455
3,Albania,ALB,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS,5.714286,5.714286,5.714286,6.428571,7.142857,7.142857,...,17.857143,20.000000,20.714286,22.857143,27.857143,27.857143,29.508197,29.508197,Upper middle income,23.793911
4,Andorra,AND,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS,14.285714,14.285714,14.285714,14.285714,28.571429,28.571429,...,50.000000,50.000000,39.285714,32.142857,32.142857,32.142857,46.428571,46.428571,High income,32.142857
6,United Arab Emirates,ARE,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,...,17.500000,17.500000,22.500000,22.500000,22.500000,22.500000,50.000000,50.000000,High income,50.000000
7,Armenia,ARM,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS,3.053435,3.053435,4.580153,5.343511,5.343511,5.343511,...,10.687023,10.687023,10.687023,10.687023,18.095238,18.095238,23.484848,23.484848,Upper middle income,20.431413
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,Samoa,WSM,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS,6.122449,6.122449,6.122449,6.122449,6.122449,6.122449,...,4.081633,6.122449,6.122449,10.000000,10.000000,10.000000,10.000000,10.000000,Lower middle income,3.877551
163,"Yemen, Rep.",YEM,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS,0.668896,0.668896,0.332226,0.332226,0.332226,0.332226,...,0.332226,0.332226,0.000000,0.000000,0.000000,0.000000,0.332226,0.332226,Low income,-0.336670
164,South Africa,ZAF,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS,29.824561,29.824561,29.824561,32.778702,32.750000,32.750000,...,42.250000,41.500000,42.000000,42.000000,41.836735,42.748092,46.347607,46.750000,Upper middle income,16.925439
165,Zambia,ZMB,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS,10.126582,12.025316,12.025316,12.025316,12.658228,14.649682,...,11.464968,10.759494,12.658228,17.964072,17.964072,17.964072,17.964072,16.766467,Lower middle income,6.639885
166,Zimbabwe,ZWE,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS,10.000000,10.000000,10.000000,10.000000,16.000000,16.666667,...,31.481481,31.481481,31.481481,31.481481,32.575758,31.481481,31.851852,31.851852,Lower middle income,21.851852

In [5]:
#create new dataframes per Incomegroup and then sort them by rate of change
df_high = df_merge[df_merge["IncomeGroup"] == "High income"]
df_high = df_high.sort_values("Rate of Change",ascending=False)
df_low = df_merge[df_merge["IncomeGroup"] == "Low income"]
df_low = df_low.sort_values("Rate of Change",ascending=False)
df_low_mid = df_merge[df_merge["IncomeGroup"] == "Lower middle income"]
df_low_mid = df_low_mid.sort_values("Rate of Change",ascending=False)
df_up_mid = df_merge[df_merge["IncomeGroup"] == "Upper middle income"]
df_up_mid = df_up_mid.sort_values("Rate of Change",ascending=False)

#create the instance of the app
app = dash.Dash(__name__)

#html layout
app.layout = html.Div([
    html.P("Years:"), #create a <p> tag with text
    dcc.Dropdown( #create a dropdown element
        id='years', #id for the dropdown element
        options=[{'value': x, 'label': x} #value is the value passed @app.callback and label is the display
                 for x in ['2001',"2020"]], # list of the options
        clearable=True # this allows you to clear the dropdown element
    ),
    html.P("Income:"),
    dcc.Dropdown( 
        id='income',
        options=[{'value': x, 'label': x} 
                 for x in ['High income',"Low income","Lower middle income","Upper middle income"]],
        clearable=False
    ),
    html.P("Top 5:"), 
    dcc.Dropdown(
        id='movers',
        options=[{'value': x, 'label': x} 
                 for x in ['Top 5 Increases',"Top 5 Decreases"]],
        clearable=True
    ),
    dcc.Graph(id="chart"), #create a graph element to display the plotly figure
])

@app.callback( # this gets called everytime a element is changed (dropdown option changes)
    Output("chart", "figure"), # chart is the graph element and figure is the return from generate_chart
    [Input("years", "value"), # years is the id for one of the dropdown abd the value gets passed to generate_chart
    Input("income", "value"), # income is the id for one of the dropdown abd the value gets passed to generate_chart
    Input("movers", "value")]) # movers is the id for one of the dropdown abd the value gets passed to generate_chart
     
def generate_chart(values,income,movers): # this gets called with the values from the input of @app.callback
    if income == "High income": # checks to see with income dropdown option is picked
        fig = px.bar(df_high,x = "Country Name",y = values,text_auto = ".3s") # create a bar chart with the values from high income dataframe
        if movers == "Top 5 Increases": # checks to see if there is an option picked for top 5 dropdown element
            fig = px.line(top(df_high.head(5)),x = "year", y = "data",color='Country Name') # create a line chart with the data from the top 5 elements in the high income dataframe
        if movers == "Top 5 Decreases": # same but bottom 5
            fig = px.line(top(df_high.tail(5)),x = "year", y = "data",color='Country Name')

    elif income == "Low income":
        fig = px.bar(df_low,x = "Country Name",y = values,text_auto = ".3s")
        if movers == "Top 5 Increases":
            fig = px.line(top(df_low.head(5)),x = "year", y = "data",color='Country Name')
        if movers == "Top 5 Decreases":
            fig = px.line(top(df_low.tail(5)),x = "year", y = "data",color='Country Name')

    elif income == "Lower middle income":
        fig = px.bar(df_low_mid,x = "Country Name",y = values,text_auto = ".3s")
        if movers == "Top 5 Increases":
            fig = px.line(top(df_low_mid.head(5)),x = "year", y = "data",color='Country Name')
        if movers == "Top 5 Decreases":
            fig = px.line(top(df_low_mid.tail(5)),x = "year", y = "data",color='Country Name')

    elif income == "Upper middle income":
        fig = px.bar(df_up_mid,x = "Country Name",y = values,text_auto = ".3s")
        if movers == "Top 5 Increases":
            fig = px.line(top(df_up_mid.head(5)),x = "year", y = "data",color='Country Name')
        if movers == "Top 5 Decreases":
            fig = px.line(top(df_up_mid.tail(5)),x = "year", y = "data",color='Country Name')

    return fig

#start the app
app.run_server()